version: '3.8'

services:
  user-service:
    image: user-service:latest
    build:
      context: ./UserService
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IoTManagementDeviceUserDB=Host=localhost;Database=IoTManagementDeviceUserDB;Username=postgres;Password=root
    depends_on:
      - userdb

  userdb:
    image: postgres:13
    environment:
      POSTGRES_DB: IoTManagementDeviceUserDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"